//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.31 at 02:00:19 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://sourceforge.net/projects/selflet/")
package it.polimi.elet.selflet.utilities.parser;
