//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.31 at 02:00:19 PM CEST 
//


package it.polimi.elet.selflet.utilities.parser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for selfletProperties complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="selfletProperties">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="author" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;choice>
 *           &lt;element name="passive" type="{http://sourceforge.net/projects/selflet/}empty"/>
 *           &lt;element name="active" type="{http://sourceforge.net/projects/selflet/}activeType"/>
 *         &lt;/choice>
 *         &lt;element name="reds" type="{http://sourceforge.net/projects/selflet/}redsType"/>
 *         &lt;element name="generalknowledge" type="{http://sourceforge.net/projects/selflet/}generalKnowledgeType" minOccurs="0"/>
 *         &lt;element name="typeKnowledge" type="{http://sourceforge.net/projects/selflet/}typeKnowledgeType" minOccurs="0"/>
 *         &lt;element name="enableOptimizationPolicy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="enableCloudOptimizationPolicy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "selfletProperties", propOrder = {
    "author",
    "description",
    "passive",
    "active",
    "reds",
    "generalknowledge",
    "typeKnowledge",
    "enableOptimizationPolicy",
    "enableCloudOptimizationPolicy"
})
public class SelfletProperties {

    @XmlElement(required = true)
    protected String author;
    @XmlElement(required = true)
    protected String description;
    protected Empty passive;
    protected ActiveType active;
    @XmlElement(required = true)
    protected RedsType reds;
    protected GeneralKnowledgeType generalknowledge;
    protected TypeKnowledgeType typeKnowledge;
    @XmlElement(defaultValue = "false")
    protected Boolean enableOptimizationPolicy;
    @XmlElement(defaultValue = "false")
    protected Boolean enableCloudOptimizationPolicy;

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthor(String value) {
        this.author = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the passive property.
     * 
     * @return
     *     possible object is
     *     {@link Empty }
     *     
     */
    public Empty getPassive() {
        return passive;
    }

    /**
     * Sets the value of the passive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Empty }
     *     
     */
    public void setPassive(Empty value) {
        this.passive = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveType }
     *     
     */
    public ActiveType getActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveType }
     *     
     */
    public void setActive(ActiveType value) {
        this.active = value;
    }

    /**
     * Gets the value of the reds property.
     * 
     * @return
     *     possible object is
     *     {@link RedsType }
     *     
     */
    public RedsType getReds() {
        return reds;
    }

    /**
     * Sets the value of the reds property.
     * 
     * @param value
     *     allowed object is
     *     {@link RedsType }
     *     
     */
    public void setReds(RedsType value) {
        this.reds = value;
    }

    /**
     * Gets the value of the generalknowledge property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralKnowledgeType }
     *     
     */
    public GeneralKnowledgeType getGeneralknowledge() {
        return generalknowledge;
    }

    /**
     * Sets the value of the generalknowledge property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralKnowledgeType }
     *     
     */
    public void setGeneralknowledge(GeneralKnowledgeType value) {
        this.generalknowledge = value;
    }

    /**
     * Gets the value of the typeKnowledge property.
     * 
     * @return
     *     possible object is
     *     {@link TypeKnowledgeType }
     *     
     */
    public TypeKnowledgeType getTypeKnowledge() {
        return typeKnowledge;
    }

    /**
     * Sets the value of the typeKnowledge property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeKnowledgeType }
     *     
     */
    public void setTypeKnowledge(TypeKnowledgeType value) {
        this.typeKnowledge = value;
    }

    /**
     * Gets the value of the enableOptimizationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableOptimizationPolicy() {
        return enableOptimizationPolicy;
    }

    /**
     * Sets the value of the enableOptimizationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableOptimizationPolicy(Boolean value) {
        this.enableOptimizationPolicy = value;
    }

    /**
     * Gets the value of the enableCloudOptimizationPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEnableCloudOptimizationPolicy() {
        return enableCloudOptimizationPolicy;
    }

    /**
     * Sets the value of the enableCloudOptimizationPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEnableCloudOptimizationPolicy(Boolean value) {
        this.enableCloudOptimizationPolicy = value;
    }

}
