//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.31 at 02:00:19 PM CEST 
//


package it.polimi.elet.selflet.utilities.parser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for serviceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="serviceType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="input" type="{http://sourceforge.net/projects/selflet/service}serviceInputType"/>
 *         &lt;element name="output" type="{http://sourceforge.net/projects/selflet/service}serviceOutputType"/>
 *         &lt;element name="revenue" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="maxResponseTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="serviceDemand" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="offerMode" type="{http://sourceforge.net/projects/selflet/service}offerModeType" />
 *       &lt;attribute name="active" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "serviceType", namespace = "http://sourceforge.net/projects/selflet/service", propOrder = {
    "input",
    "output",
    "revenue",
    "maxResponseTime",
    "serviceDemand"
})
public class ServiceType {

    @XmlElement(required = true)
    protected ServiceInputType input;
    @XmlElement(required = true)
    protected ServiceOutputType output;
    protected double revenue;
    protected double maxResponseTime;
    protected double serviceDemand;
    @XmlAttribute
    protected String name;
    @XmlAttribute
    protected OfferModeType offerMode;
    @XmlAttribute
    protected Boolean active;

    /**
     * Gets the value of the input property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceInputType }
     *     
     */
    public ServiceInputType getInput() {
        return input;
    }

    /**
     * Sets the value of the input property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceInputType }
     *     
     */
    public void setInput(ServiceInputType value) {
        this.input = value;
    }

    /**
     * Gets the value of the output property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceOutputType }
     *     
     */
    public ServiceOutputType getOutput() {
        return output;
    }

    /**
     * Sets the value of the output property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceOutputType }
     *     
     */
    public void setOutput(ServiceOutputType value) {
        this.output = value;
    }

    /**
     * Gets the value of the revenue property.
     * 
     */
    public double getRevenue() {
        return revenue;
    }

    /**
     * Sets the value of the revenue property.
     * 
     */
    public void setRevenue(double value) {
        this.revenue = value;
    }

    /**
     * Gets the value of the maxResponseTime property.
     * 
     */
    public double getMaxResponseTime() {
        return maxResponseTime;
    }

    /**
     * Sets the value of the maxResponseTime property.
     * 
     */
    public void setMaxResponseTime(double value) {
        this.maxResponseTime = value;
    }

    /**
     * Gets the value of the serviceDemand property.
     * 
     */
    public double getServiceDemand() {
        return serviceDemand;
    }

    /**
     * Sets the value of the serviceDemand property.
     * 
     */
    public void setServiceDemand(double value) {
        this.serviceDemand = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the offerMode property.
     * 
     * @return
     *     possible object is
     *     {@link OfferModeType }
     *     
     */
    public OfferModeType getOfferMode() {
        return offerMode;
    }

    /**
     * Sets the value of the offerMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferModeType }
     *     
     */
    public void setOfferMode(OfferModeType value) {
        this.offerMode = value;
    }

    /**
     * Gets the value of the active property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isActive() {
        return active;
    }

    /**
     * Sets the value of the active property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setActive(Boolean value) {
        this.active = value;
    }

}
